global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/<id>/<another-id>'
route:
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#slack-notify-playground'
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      send_resolved: true
      title: '{{ template "custom_title" . }}'
      text: '{{ template "custom_slack_message" . }}'

templates:
- '/home/ubuntu/alertmanager-0.21.0.linux-amd64/notifications.tmpl'